containers:
- name: myapp
  image: demodotnet.azurecr.io/myapp:29

  ports:
  - containerPort: 8080   # ✅ NOT 80

  env:
  - name: ASPNETCORE_URLS
    value: http://+:8080  # ✅ MATCH PORT

  readinessProbe:
    httpGet:
      path: /
      port: 8080

  livenessProbe:
    httpGet:
      path: /
      port: 8080
