apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: demo

spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"       
    userAssignedIdentityID: ""          
    keyvaultName: "dotnetdemoo"

    objects: |
      array:
        - |
          objectName: ExternalApiKey
          objectType: secret

    tenantId: "2d59024c-c435-43ba-a6ce-9c48054d6c53"
