apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    keyvaultName: "dotnetdemo"

    objects: |
      array:
        - |
          objectName: ExternalApiKey
          objectType: secret

    tenantId: "2d59024c-c435-43ba-a6ce-9c48054d6c53"

    clientID: "a9e96738-c906-44d9-8d4d-0cb615cf3b54"
