apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: demo

spec:
  selector:
    app: myapp

  ports:
  - protocol: TCP
    port: 80          # ✅ Service Port
    targetPort: 8080  # ✅ Container Port

  type: ClusterIP
